spring.application.name=gerenciador-senhas-api

spring.datasource.url=jdbc:postgresql://localhost:5432/gerenciador_senhas
spring.datasource.username=postgres
spring.datasource.password=22426230

spring.jpa.hibernate.ddl-auto=update